apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
data:
  flink-conf.yaml: |
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    jobmanager.rpc.address: flink-jobmanager
    jobmanager.heap.size: 4096m
    taskmanager.heap.size: 4096m
    taskmanager.numberOfTaskSlots: 2


